#!/usr/bin/env node
// Generated by CoffeeScript 1.12.7
var argv, asSentence, context, filename, flatten, fs, generate, grammar, k, minimist, parse, randomChoice, ref, splitToken, v;

fs = require('fs');

minimist = require('minimist');

ref = require('./helpers'), randomChoice = ref.randomChoice, flatten = ref.flatten, splitToken = ref.splitToken, asSentence = ref.asSentence;

parse = require('./parse');

generate = require('./generate');

argv = minimist(process.argv.slice(2));

filename = process.argv[2];

if (filename == null) {
  console.log("Usage: nalgene [file.nlg] (--key=value...)");
  process.exit();
}

grammar = parse(fs.readFileSync(filename, 'utf8'));

context = {};

for (k in argv) {
  v = argv[k];
  context['$' + k] = v;
}

console.log(generate(grammar, context));
