// Generated by CoffeeScript 1.12.4
var generate;

module.exports = generate = function(grammar, context, entry_key) {
  if (entry_key == null) {
    entry_key = '%';
  }
  console.log('generate with', context, 'from', entry_key);
  console.log(grammar.get(entry_key).toString());
  return '';
};
