// Generated by CoffeeScript 2.3.1
var util;

util = require('util');

exports.inspect = function(tag, o) {
  return console.log(`[${tag}]`, util.inspect(o, {
    colors: true,
    depth: null
  }));
};

exports.sortBy = function(l, fn) {
  return l.sort(function(a, b) {
    return fn(b) - fn(a);
  });
};

exports.flatten = function(ls) {
  var flat, i, j, k, l, len, len1;
  flat = [];
  for (j = 0, len = ls.length; j < len; j++) {
    l = ls[j];
    for (k = 0, len1 = l.length; k < len1; k++) {
      i = l[k];
      flat.push(i);
    }
  }
  return flat;
};

exports.randomChoice = function(l) {
  return l[Math.floor(Math.random() * l.length)];
};

exports.fixPunctuation = function(s) {
  s = s.trim().replace(/\s+/g, ' ');
  s = s.replace(/\ ([,.!?:])/g, '$1');
  s = s.trim();
  return s;
};
