// Generated by CoffeeScript 2.3.1
var util;

util = require('util');

exports.inspect = function(tag, o) {
  return console.log(`[${tag}]`, util.inspect(o, {
    colors: true,
    depth: null
  }));
};

exports.sortBy = function(l, fn) {
  return l.sort(function(a, b) {
    return fn(b) - fn(a);
  });
};

exports.flatten = function(ls) {
  var flat, i, j, l, len, len1, m;
  flat = [];
  for (j = 0, len = ls.length; j < len; j++) {
    l = ls[j];
    for (m = 0, len1 = l.length; m < len1; m++) {
      i = l[m];
      flat.push(i);
    }
  }
  return flat;
};

exports.usedKeys = function(o) {
  var k, ks, v;
  ks = [];
  for (k in o) {
    v = o[k];
    if (v != null) {
      ks.push(k);
    }
  }
  return ks;
};

exports.randomChoice = function(l) {
  return l[Math.floor(Math.random() * l.length)];
};

exports.fixPunctuation = function(s) {
  s = s.trim().replace(/\s+/g, ' ');
  s = s.replace(/\ ([,.!?:])/g, '$1');
  s = s.trim();
  return s;
};
