// Generated by CoffeeScript 1.12.4
var Tree, helpers, parse;

helpers = require('./helpers');

Tree = require('./tree');

module.exports = parse = function(grammar) {
  var current_index, i, ii, j, k, len, lines, ref, ref1, root, s, tree;
  lines = grammar.split('\n').map(helpers.countIndentation).filter(helpers.isALine);
  root = new Tree(null, '^', -1);
  tree = root;
  current_index = -1;
  for (j = 0, len = lines.length; j < len; j++) {
    ref = lines[j], i = ref[0], s = ref[1];
    if (i === current_index) {
      tree = tree.addSibling(s, i);
    } else if (i > current_index) {
      tree = tree.addChild(s, i);
    } else if (i < current_index) {
      for (ii = k = 0, ref1 = i - tree.level; 0 <= ref1 ? k < ref1 : k > ref1; ii = 0 <= ref1 ? ++k : --k) {
        tree = tree.parent;
      }
      tree = tree.addSibling(s, i);
    }
    current_index = i;
  }
  return root;
};
